name: wine
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^4.1.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  flutter_native_splash: ^2.2.9
  webview_flutter: ^3.0.4
  device_info_plus: ^4.1.2
  camera: ^0.10.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/specials.png
    - assets/images/cellar.png
    - assets/images/grapes.png
    - assets/images/bottles.png
    - assets/images/bar.png
    - assets/images/dummy_bottle.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
